config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'home#index'
  resources :maps, expect: %w[destroy]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base # :nodoc:
  self.abstract_class = true
end

app/models/map.rb
# frozen_string_literal: true

class Map < ApplicationRecord # :nodoc:
  belongs_to :user
  has_many :pins, dependent: :destroy

  scope :mine, ->(uzer) { where(user: uzer) }

  def owner?(uzer)
    user == uzer
  end
end

app/models/pin.rb
# frozen_string_literal: true

class Pin < ApplicationRecord # :nodoc:
  belongs_to :map
end

app/models/user.rb
# frozen_string_literal: true

class User < ::ApplicationRecord # :nodoc:
  # Include default devise modules. Others available are:
  # :timeoutable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable,
         :lockable,
         :omniauthable, omniauth_providers: %i[facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      # user.name = auth.info.name # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      user.skip_confirmation!
    end
  end

  def name_title
    "#{try(:name)}さん"
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController # :nodoc:
  def index
    @maps = Map.mine(current_user)
  end
end

app/controllers/maps_controller.rb
# frozen_string_literal: true

class MapsController < ApplicationController # :nodoc:
  before_action -> { @map = Map.find(params[:id]) }, only: %i[show edit]

  def index
    @q = Map.ransack(params[:q])
    @maps = @q.result(distinct: true).includes(:user)
  end

  def new; end

  def create
    map = Map.new(map_params)
    if map.save
      render json: { code: 200, data: map }
    else
      render json: { code: 500, msg: 'some error occure.' }
    end
  end

  def update
    map = Map.find(params[:id])
    return render json: { code: 500, msg: 'this is not your map.' } unless map.user_id == current_user.id

    if map.update(map_params)
      render json: { code: 200, data: map }
    else
      render json: { code: 500, msg: 'some error occure.' }
    end
  end

  def show; end

  def edit; end

  private

  def map_params
    params.require(:map).permit(:name).merge(user: current_user)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController # :nodoc:
    def facebook
      @user = User.from_omniauth(request.env['omniauth.auth'])
      @user.save! unless @user.persisted?

      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    end

    def failure
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper # :nodoc:
  def googlemap_include_tag(callback: nil, async: true)
    url = if callback.present?
            "https://maps.googleapis.com/maps/api/js?key=#{Settings.googlemap.key}&callback=#{callback}"
          else
            "https://maps.googleapis.com/maps/api/js?key=#{Settings.googlemap.key}"
          end

    if async
      javascript_include_tag url, async: 'async'
    else
      javascript_include_tag url
    end
  end
end

app/views/home/index.html.slim
.container
  .row
    .col-lg
      = link_to maps_path do
        .card
          .card-body
            h5 探す
    - if user_signed_in?
      .col-lg
        = link_to new_map_path do
          .card
            .card-body
              h5 作る

.content-center[style='margin-top: 30px;']
  h3
    - if user_signed_in?
      = "#{current_user.name_title}の地図一覧"
  .row
    - @maps.each do |map|
      .col-lg
        = link_to map_path(map) do
          = map.as_html_card

app/views/layouts/_header.html.slim
header.paper-shadow
  .header-container.content-center
    = link_to root_path do
      h1.logo THE MAP SHOP

    - if user_signed_in?
      nav
        ul.nav.nav-pills.nav-fill.dropmenu
          li.nav-item
            = link_to current_user.name_title, '#', class: 'nav-link'
            ul
              li
                = link_to 'ログアウト', destroy_user_session_path, method: :delete
          li.nav-item
          li.nav-item
          li.nav-item
          li.nav-item
    - else
      section
        p
          | THE MAP SHOP is a platform aim to exchange your knowledge to money.
          br
          | for example, the list of coffee shops, onsen hotels or any other places you recommended.
          br
          | you can post them here as free or as commerce.

      section
        | seeing is believing.
        br
        | LET'S SIGN UP
        =< link_to 'here', new_user_session_path
        | .

app/views/layouts/application.html.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    title TheMapShop
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = javascript_pack_tag    'application'
  body
    = render 'layouts/header'

    /! devise message
    - if notice || alert
      p.notice= notice
      p.alert= alert

    = yield

app/views/maps/edit.html.slim
.container
  h2 地図の編集
  #map-form data-props="#{@map.to_json(include: :pins)}"

app/views/maps/index.html.slim
= search_form_for @q do |f|
  .form-group.row
    .col-sm-2
    .col-sm-6
      = f.search_field :name_or_user_name_cont, class: 'form-control', placeholder: 'フリーワード検索'
    .col-sm-2
      = f.submit 'submit', class: 'btn btn-primary mb-2'
    .col-sm-2

.content-center
  .row
    - @maps.each do |map|
      .col-lg
        = link_to map_path(map) do
          = map.as_html_card

app/views/maps/new.html.slim
= googlemap_include_tag(async: false)

.container
  h2 地図の編集
  #map-form data-props="#{{pins: []}.to_json}"

app/views/maps/show.html.slim
= @map.as_html_card

.content-center
  #gmap[style="width:100%;height:400px;"]
  .pins-data-list
    - @map.pins.each do |pin|
      = pin.as_html_data
= googlemap_include_tag callback: 'initMapsShowGmap'